### ISSUE TITLE
Module error on run

### ISSUE THREAD

**Issue by fharper** [Botfuel/sample-bot-botbuilder-qna#1]
I installed all modules, but when I start the node server, I got this error:

```
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/fharper/Documents/Code/sample-bot-botbuilder-qna/node_modules/dtrace-provider/dtrace-provider.js:18:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by kevinadda** [comment]
@fharper I cannot reproduce, can you tell me what version of node you are using? You can take a look at [this post](https://stackoverflow.com/questions/37550100/cannot-find-module-dtrace-provider), in a nutshell:
- Upgrade Node if <= 6.0;
- Try removing node modules and reinstalling with: `npm install --no-optional`;
- If ever you have xcode but never used it, you may need to accept the license agreement.

**Comment by fharper** [comment]
Thanks for the quick answer @kevinadda. Sorry, totally forgot the Node version: 6.11.2.

Not installing optional dependencies did the trick, thanks.
